#!/bin/sh
# today-log - concatenate today journals in reverse chronological order
# SPDX-FileCopyrightText: 2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

TODAY_DIR="${TODAY_DIR:-${XDG_DATA_HOME:-${HOME}/.local/share}/today}"
TODAY_SUFFIX="${TODAY_SUFFIX:-.gmi}"

name_pat="[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$TODAY_SUFFIX"
find "$TODAY_DIR" -type f -name "$name_pat" | sort -r | while IFS= read -r f
do
	if [ "$TODAY_SUFFIX" = '.gmi' -o "$TODAY_SUFFIX" = '.md' ]
	then
		# Add a header with the journal date and increase the level of
		# headers in the journal by one.
		printf '# %s\n\n' "$(basename "$f" "$TODAY_SUFFIX")"
		sed 's/^#/##/' "$f"
	else
		printf '%s\n\n' "$(basename "$f" "$TODAY_SUFFIX")"
		cat "$f"
	fi
	printf '\n\n\n'
done
